DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE MEMBER_LEVEL CASCADE CONSTRAINTS;
DROP SEQUENCE MEMBER_MNO_SQ;

CREATE TABLE MEMBER_LEVEL (
    LEVELNO NUMBER PRIMARY KEY,
    LEVELNAME VARCHAR2(50) NOT NULL
);

CREATE TABLE MEMBER (
    mNO NUMBER PRIMARY KEY,
    mNAME VARCHAR2(50) NOT NULL,
    mPW VARCHAR2(8) NOT NULL,
    mMAIL VARCHAR2(50) UNIQUE NOT NULL,
    mPOINT NUMBER DEFAULT 0 CHECK (mPOINT >= 0),
    mRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER,
    CONSTRAINT fk_level FOREIGN KEY (LEVELNO) REFERENCES MEMBER_LEVEL(LEVELNO)
);

CREATE SEQUENCE MEMBER_MNO_SQ
START WITH 1
INCREMENT BY 1
NOCACHE;

-- MEMBER_LEVEL 데이터 입력
INSERT INTO MEMBER_LEVEL VALUES (0, '일반고객');
INSERT INTO MEMBER_LEVEL VALUES (1, '실버고객');
INSERT INTO MEMBER_LEVEL VALUES (2, '골드고객');
INSERT INTO MEMBER_LEVEL VALUES (-1, 'black');

-- MEMBER 데이터 입력
INSERT INTO MEMBER (
    mNO, mNAME, mPW, mMAIL, mPOINT, mRDATE, LEVELNO
) VALUES (
    MEMBER_MNO_SQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, TO_DATE('2022-03-10', 'YYYY-MM-DD'), 0
);

INSERT INTO MEMBER (
    mNO, mNAME, mPW, mMAIL, mPOINT, mRDATE, LEVELNO
) VALUES (
    MEMBER_MNO_SQ.NEXTVAL, '신길동', 'bb', 'sin@sin.com', 1000, TO_DATE('2022-04-01', 'YYYY-MM-DD'), 1
);

SELECT 
    mNO AS "mNO",
    mNAME AS "mNAME",
    TO_CHAR(mRDATE, 'YYYY-MM-DD') AS "mRDATE",
    mMAIL AS "mMAIL",
    mPOINT AS "point",
    LEVELNAME AS "levelname"
FROM 
    MEMBER
JOIN 
    MEMBER_LEVEL ON MEMBER.LEVELNO = MEMBER_LEVEL.LEVELNO;
